# Keep this file as small as possible! Only explicit imports here!
name: pubtrends
channels:
  - anaconda
  - conda-forge
  - bokeh
  - pytorch
dependencies:
  - bokeh=3.6.3
  - cachetools=5.5.2
  - celery=5.4.0
  - ipywidgets=8.1.5
  - holoviews=1.20.1
  - huggingface_hub=0.29.1
  - flask=3.1.0
  - matplotlib=3.10.1
  - nltk=3.9.1
  - pandas=2.2.3
  - parameterized=0.9.0
  - python=3.10.16
  - pytest=8.3.5
  - psycopg2=2.9.9
  - wordcloud=1.9.4
  - networkx=3.4.2
  - python-louvain=0.16
  - scikit-learn=1.6.1
  - pytorch=2.5.1
  - transformers=4.49.0
  - tensorboardx=2.6.2.2
  - psutil=7.0.0
  - unidecode=1.3.8
  - pip
  - pip:
      - email-validator==2.2.0
      - flask-admin==1.6.0
      - flask-security==5.6.0
      - flask-sqlalchemy==3.1.1
      - gunicorn==23.0.0
      - lazy==1.6
      - rouge==1.0.1
      - redis==5.2.1
      - vine==5.1.0
